# Generated by Django 6.0.7 on 2026-08-01 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=150)),
                ("position", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("saved", "Saved"),
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interviewing", "Interviewing"),
                            ("offer", "Offer"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="saved",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("job_url", models.URLField(blank=True, max_length=500)),
                ("contact_name", models.CharField(blank=True, max_length=150)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("salary", models.CharField(blank=True, max_length=100)),
                ("applied_date", models.DateField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
